opentracing/opentracing-go

Makefile, examples/dapperish.go, examples/dapperish/dapper.go, examples/dapperish/random.go, examples/dapperish/trivialrecorder.go, opentracing/ext/tags.go, opentracing/ext/tags_test.go, opentracing/raw.go, opentracing/span.go, opentracing/standardtracer/standardimpl.go, testutils/assert/assert.go, testutils/assert/assert_test.go, testutils/recorder.go, testutils/recorder_test.go, testutils/trace_context.go, testutils/trace_context_test.go
=> Adds ext/tags mechanism for adding common tags to the span

opentracing/utils.go
- Remove `OpenTracing` prefix as the package is already `opentracing`.
- Add some whitespace between the comments.
=> opentracing: make HTTP header prefix constants more readable

opentracing/ext/tags.go, opentracing/ext/tags_test.go
- No need for struct because there is only one field.
- Do not place the values on the heap / use pointer as they are small.
=> opentracing/ext: simplify internal tag types

gocontext.go
The line
```go
val := ctx.Value(activeSpanKey)
```
previously allocated to pass the integer
`activeSpanKey` as an interface. With this
change, no such allocation is necessary.
This showed up during benchmarks in
cockroachdb/cockroach.
=> Use struct{} instead of int as context key

standardtracer/spanpropagator.go, standardtracer/spanpropagator_test.go
Fixed the following bugs:
- JoinTraceFromBinary reconstructed, but didn't use the
attributes map
- JoinTraceFromBinary contained calls to binary.Read which
attempted to read into type `int`, which is a runtime panic.
- JoinTraceFromText did not create a new span, but returned a
Span with identical SpanID and no parent instead.
Added a test that exercises all of the above.
Two further commits contain unrelated minor fixes.
=> Fix multiple bugs in standard SpanPropagator

globaltracer.go, noop.go, span.go, utils.go
It is used as the default value for the
package-level singleton, but allowing
external packages to make use of it is
a benefit.
Minor other code changes to have passing
`go vet ./...` and `golint`.
Any plans for CI on this repo? The current
state of affairs is somewhat sad.
=> Export NoopTracer

standardtracer/spanpropagator.go
namely setting Sampled on the child whenever
it was **not** set on the parent.
Caught by the test from #42. Much can be won
by a simple one-liner setup on Travis/CircleCI,
pre-stabilization or not. The current situation
is frankly a little insane.
Happy to set that up, just need the corresponding
rights on the repository.
=> Fix the fix in #44

examples/dapperish.go, ext/tags_test.go, globaltracer.go, noop.go, span.go, standardtracer/span.go, standardtracer/spanpropagator.go, standardtracer/spanpropagator_test.go, standardtracer/tracer.go, tracer.go
While we're at it, add support for Span start/finish options.
@yurishkuro I am amused by the similarity between the Start/FinishOptions and some RFC Go code you sent out in the early days of the DCP discussion late last year. I didn't actually reference it, but if memory serves this is similar.
See also:
- https://github.com/opentracing/opentracing.github.io/issues/44#issuecomment-179654948
- https://github.com/opentracing/opentracing.github.io/issues/22
- https://github.com/opentracing/opentracing.github.io/issues/20, which is basically a dup of 22 just above
- https://github.com/opentracing/opentracing.github.io/issues/43 (perhaps the start options could accomplish this via an explicit Tag)
=> consolidate span creation methods

standardtracer/propagation.go, standardtracer/propagation_test.go, standardtracer/raw.go, standardtracer/span.go, standardtracer/tracer.go
The implicit import name makes resolution easier for
tools like `godef`, which at the time of writing do
not have the capability to resolve nonstandard
import paths, for example see
https://github.com/rogpeppe/godef/issues/18
I looked into adding it for `godef`, but it did not
seem trivial.
=> Import opentracing-go as opentracing

.travis.yml, Makefile, examples/dapperish/trivialrecorder.go, noop.go, propagation.go, span.go, standardtracer/bench_test.go, standardtracer/propagation.go, standardtracer/raw.go, standardtracer/recorder.go, standardtracer/span.go, standardtracer/standardcontext.go, standardtracer/tracer.go, standardtracer/util.go, testutils/recorder.go, testutils/recorder_test.go
Embed StandardContext (not *StandardContext) into
RawSpan and initialize the attribute and tags map
only on the first write (it is valid to read from
a nil map).
Move the trace attributes from StandardContext onto
spanImpl; they were not exposed to the recorder, and
the lock on StandardContext required that object to
always be heap allocated. If they need to be exposed
to the user, they can be moved onto RawSpan (or even
back onto StandardContext, but without the lock).
Locking is instead synchronized through the Span's
log.
Work towards sane allocation behavior and add some
benchmarks to that effect: Span creation and destruction
with calls to LogEvent, SetTag oder SetTraceAttribute
now don't allocate.
Changed various other pointers to be passed by-value.
Fix various linter errors and …
=> Avoid allocations, fix CI

ext/tags.go, span.go, standardtracer/bench_test.go, standardtracer/propagation.go, standardtracer/span.go, standardtracer/tracer.go
Introduce the Options type and corresponding Tracer
constructor NewWithOptions.
Options currently include a user-provided sample
function (i.e. a mapping from TraceID to boolean),
the SpanRecorder, and the option to ignore logs,
attributes and tags (except ext.SamplingPriority)
on non-sampled Spans for performance.
Support ext.SamplingPriority in standardtracer.
This needs a few unit tests, but I wanted to get into
the discussion first. The motivation for this change is
wanting to use `standardtracer` in [cockroachdb/cockroach](https://github.com/cockroachdb/cockroach);
these are some basic changes which make relevant
functionality available.
Added benchmark which demonstrates that a `trimmed` Span behaves
effectively like a no-op span, except that there will still be serialization …
=> Add dynamic configuration

propagation.go, standardtracer/bench_test.go, standardtracer/propagation.go
Pick some (but not all) low hanging fruit. For example, the encoding
in `github.com/cockroachdb/cockroach/util/encoding` has primitives
better suited to providing an efficient wire encoding.
```
name                                 old time/op    new time/op    delta
Inject_SplitBinary_Empty-8              792ns ± 1%     825ns ± 4%   +4.26%        (p=0.006 n=10+10)
Inject_SplitBinary_100Attributes-8     98.6µs ± 2%    38.0µs ± 2%  -61.48%        (p=0.000 n=10+10)
Extract_SplitBinary_Empty-8             882ns ± 1%     885ns ± 1%     ~            (p=0.287 n=9+10)
Extract_SplitBinary_100Attributes-8     155µs ± 1%      67µs ± 4%  -56.87%        (p=0.000 n=10+10)
name                                 old alloc/op   new alloc/op   delta
Inject_SplitBinary_Empty-8               352B ± 0% …
```
=> Add benchmarks for serialization, and make some improvements

LICENSE
Per https://github.com/opentracing/opentracing-go/issues/56
=> add the apparently-missing MIT license file

ext/tags.go, ext/tags_test.go
Brings Go in parity with Python, where span kind tags have been defined for a while.
=> Change common tags to use Set instead of Add method. Add Span Kind.

ext/tags_test.go, noop.go, propagation.go, span.go, tracer.go, utils.go
Per https://github.com/opentracing/opentracing.github.io/issues/70 . The Tracer.Injector() calls were going to be 1:1 with Injector.InjectSpan() calls, and the Tracer.Extractor() calls were going to be 1:1 with Extractor.JoinTrace() calls; this change cuts out the middleman.
@tschottdorf @bg451 @yurishkuro what do we want to do about `basictracer-go`? I can do this change in a way that breaks nothing there (i.e., temporarily support both APIs in OT-go, remove all deps on the old one, remove old API, etc, etc) or I can stage a change in `basictracer-go` and merge the two in close succession. No strong feelings either way but wanted to check whether anyone is depending on `basictracer-go` in a way where that sort of short-term breakage is unacceptable. (If so, I will obviously do the …
=> Simplify propagation by removing an API layer

gocontext.go, gocontext_test.go
Per gitter conversation, returning the input span is only useful in very specialized cases, like this:
```go
ctx, span := opentracing.ContextWithSpan(ctx, tracer.StartSpan(…))
```
=> Change Go-Context methods not to return the input span

utils.go
`JoinFromHeader` now creates the appropriate map if the `SplitTextCarrier`'s map are nil, since `NewSplitTextCarrier` doesn't create any maps. This fixes a nil map assignment bug for when a `Tracer` doesn't implement `Join` for `GoHTTPHeader` and tries to use `Join` for `SplitText`.
Here's the panic in action.
```
2016/03/05 09:46:59 http: panic serving [::1]:51661: assignment to entry in nil map
goroutine 11 [running]:
net/http.(*conn).serve.func1(0xc8200c7b80, 0x86edd0, 0xc820032168)
/usr/local/go/src/net/http/server.go:1287 +0xb5
github.com/opentracing/opentracing-go.JoinFromHeader(0x4ecba0, 0xa, 0xc82019a000, 0x86ec00, 0xc820118e10, 0x0, 0x0, 0x0, 0x0)
/Users/bg/go/src/github.com/opentracing/opentracing-go/utils.go:76 +0x87d
main.server.func1(0xba0058, 0xc8201a0000, 0xc82011a700) …
```
=> Fix a nil map assignment in JoinFromHeader

gocontext.go, gocontext_test.go, noop.go, testtracer_test.go
I've found myself wanting this function over and over again in my own Go instrumentation code... thoughts?
@beberlei @yurishkuro @tschottdorf @bg451 have you done something else for (safely/concisely) creating a `Span` from a `context.Context`?
=> Add StartSpanFromContext (and testTracer)

utils.go
Easier for `grep`, visual scanning, etc.
=> keep func signatures on a single line

mocktracer/mocktracer.go
See https://github.com/go-kit/kit/pull/247 where I need to use this.
=> Add a trivial MockTracer to test OT client code

Makefile, ext/tags.go, ext/tags_test.go, mocktracer/mocktracer.go, noop.go, propagation.go, span.go, testtracer_test.go
=> Support ForeachBaggageItem

README.md, ext/tags.go
it is very common for a server at the edge (ex. api gateway) to start an RPC server tagged span without a Client as the client might not have instrumentation. This change allows for clientContext to be nil
=> allow RPCServerOption to be used without a parent client

mocktracer/mocktracer.go
after the SpanContext changes the baggage test broke in the Go kit tests using Mocktracer. This fixes it.
=> fixed broken propagation of baggage in Mocktracer

options_test.go, tracer.go
Reason: to simplify span starting code by not forcing nil checks:
```go
sc, _ := tracer.Extract(someFormat, someCarrier)
span := tracer.StartSpan("operation", ChildOf(sc)) // should work even if sc == nil
```
cc @bensigelman
=> Allow nil argument to ChildOf/FollowsFrom

ext/tags_test.go, mocktracer/mocktracer.go, mocktracer/mocktracer_test.go
This change removes the Get prefix from mocktracer GetBaggage, GetTags, and GetFinishedSpans, per the Go idiom for accessor methods.
r @yurishkuro @bensigelman
=> Strip Get prefix from methods

mocktracer/mockspan.go, mocktracer/mocktracer.go, mocktracer/mocktracer_test.go, mocktracer/propagation.go
Also expose SpanContext property for easier access/validation.
The custom injectors/extractors are needed to support certain special cases when testing instrumentation code.
=> Support custom injectors/extractors in MockTracer

propagation.go
As `Tracer.Extract` does not take a first `opName` string parameter.
=> Update documentation example for HTTPHeaders BuiltinFormat

tracer.go
I was reading the documentation and found a typo, I checked the whole file, but just found this one.
Thanks for your awesome work guys! 💪
=> Fix typo in `tracer.go`

ext/tags.go, mocktracer/mocktracer.go, mocktracer/mocktracer_test.go, mocktracer/propagation.go, propagation.go
Support HTTPHeaders format in MockTracer with URL escaping
Addresses https://github.com/opentracing/opentracing.github.io/issues/113
=> Remove URL escaping from HTTPHeadersCarrier and add a test for it

gocontext.go, gocontext_test.go, testtracer_test.go
Options were ignored when creating a span.
=> Pass options along when creating a span with StartSpanFromContext

log/field.go, log/field_test.go
Currently the only way to print a `Field` is to define an `Encoder`. This is a
lot of code to write, especially if it's needed just for debugging or a quick
test. Adding a `Value()` method that returns the value as an `interface{}`
(which can be passed to `fmt.Print` functions), as well as a `String()` method.
Also exporting the key field.
CC @tschottdorf
=> Add convenience methods to log.Field

.travis.yml
```
https://travis-ci.org/opentracing/opentracing-go/jobs/179988943
$ go version
go version go1.5 linux/amd64
go.env
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/travis/gopath"
GORACE=""
GOROOT="/home/travis/.gimme/versions/go1.5.linux.amd64"
GOTOOLDIR="/home/travis/.gimme/versions/go1.5.linux.amd64/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT=""
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
install.1
2.28s$ go get -d -t github.com/opentracing/opentracing-go/...
2.63s$ go get -u github.com/golang/lint/...
../../../golang.org/x/tools/go/gcimporter15/bexport.go:557: undefined: constant.ToFloat
../../../golang.org/x/tools/go/gcimporter15/gcimporter.go:396: pkg.SetName undefined (type …
```
=> Drop Go 1.5 that fails in Travis

CHANGELOG.md, globaltracer.go, mocktracer/mocktracer_test.go, noop.go
* Clarify the purpose of NoopTracer
=> Deprecate InitGlobalTracer in favor of SetGlobalTracer

propagation.go, tracer.go
While working on TraceView's OT tracer and porting the [opentracing-python API test harness](https://github.com/opentracing/opentracing-python/blob/master/opentracing/harness/api_check.py) to Go, I noticed not all the usage examples worked against the current OT API.
I also changed "spanContext" to "clientContext" in the propagation.go HTTP Extract examples to match the name @bhs used in tracer.go — hope that is OK!
=> Fix some usage examples

README.md, log/field.go, log/field_test.go
prevents cluttering of the field list with optional fields that would otherwise be encoded as opt1:nil, opt2:nil, etc
=> Add a Skip log field type to log to allow for optional fields

ext/tags.go
=> add ipv4Tag type for `peer.ipv4` to support add ipv4 string to the `span`

Makefile, mocktracer/mockspan.go, mocktracer/mocktracer_test.go
The comments in the MockSpan struct indicate that SpanContext is guarded
by the embedded mutex, but no mutex lock is done in the Context()
implementation. This allows for a race condition, for example between
calling Context() and calling SetBaggageItem().
=> Fix race condition in MockSpan.

.travis.yml
Mainly because Go 1.6 does not allow nested tests. Go 1.8 has been released already, do we need to be testing with more than two recent versions?
=> Stop testing with Go 1.6

gocontext.go, gocontext_test.go
The `context` package was introduced in Go 1.7 as a replacement to the `golang.org/x/net/context` package.
Now that we're nearing the release of Go 1.10, we should replace the usage of `golang.org/x/net/context` with the standard library `context`.
This change requires that we drop support for Go 1.6 (#147) and resolves issue #153.
=> Replace 'golang.org/x/net/context' with 'context'

LICENSE, README.md
This commit replaces the MIT license with the Apache 2.0 license.
(All CNCF projects should use the Apache License 2.0 - please see opentracing/specification#61 for context.)
Note:
- none of the existing files has a license header, so I haven't added any headers in this commit.
- I have preserved the copyright as `Copyright 2016 The OpenTracing Authors`. Should the year be listed as 2018 instead?
Please air any objections by April 3rd, thanks!
CCing @dankohn
CCing previous contributors: @bhs @tschottdorf @yurishkuro @bg451 @jmacd @slimsag @basvanbeek @cce @stamm @RaduBerinde @gwik @sebastianvera @IncSW @bradbl @kyleconroy @bmizerany @RichardScothern @tamird @PikBot @ror6ax @dvrkps @NeoCN @savaki @rohanpai @tedsuo @billf @voutasaurus @kriskowal
=> update license to Apache 2.0

span.go
Document return types of Span functions which return a Span to indicate that they must return themselves rather than a new span.
This indicates to callers that it is safe to ignore the return value if they do not use call chaining.
Fixes #161
=> Span: add return type documentation

.gitignore, .travis.yml, Makefile
* The old `go get -u github.com/golang/lint/...` no longer works
* The new `go get -u golang.org/x/lint/golint/...` does not work in older Go versions (it uses type alias)
* Coverage was never uploaded
* Use Travis build matrix with env vars to control LINT and COVERAGE
* Only run lint and coverage on tip, not on older versions
=> Fix lint and coverage

globaltracer.go, globaltracer_test.go
This helps to identify if the global tracer is using the default NoopTracer or has had a tracer registered. This is useful for integration libraries to determine if they can/should set a tracer or use the configured global tracer.
This was first discussed in opentracing/opentracing-csharp#113
=> Add support to GlobalTracer to indicate if a tracer has been registered

ext/tags.go, harness/api_checkers.go, harness/noop_api_test.go
Because these package names are short and they are unique, it can not conflict. So the import aliases that can be omitted and we should remove them.
=> Fix redundant import alias

CHANGELOG.md, README.md
For security, we should change http into https links.
=> Change http to https for security links

mocktracer/mocktracer.go
I think when the passed `SpanContext` is not type of `MockSpanContext`, the error should be `ErrInvalidSpanContext` and not the `ErrInvalidCarrier`
=> Fix returned error for Inject

log/field.go
improve documentation for log.Object() to emphasize the requirement to pass immutable arguments 
#218
=> improve documentation for log.Object()

ext/field.go, ext/field_test.go, log/field.go, log/field_test.go
Opentracing spec specify prefered names for log messages [1]
This patch adds declaration for fields which are meaningful for golan
I've added only minimal subset of features as a first step,
For example this patch has no stacktrace logging for errors because  stacktrace generation is implementation depended, so caller should do it explicitly.
Footnotes:
[1] https://github.com/opentracing/specification/blob/master/semantic_conventions.md
=> ext: Add LogFields helpers for keys from specification

log/util.go, log/util_test.go
This causes a panic that will be recovered by the fmt package.
Althought on darwin this makes any projects using open tracing impossible to debug with dlv
see https://github.com/cortexproject/cortex/issues/1712
Signed-off-by: Cyril Tovena <cyril.tovena@gmail.com>
=> Set nil pointer to string nil when converting key values.

log/field.go, log/field_test.go
The OpenTracing Specification suggests "error.object" as the log
key for an error object.
Fixes #164
=> OpenTracing Semantic Conventions uses error.object

.travis.yml, ext/field_test.go, gocontext.go, gocontext_test.go
This got broken by #220. Adding a unit test.
=> Restore the ability to reset current span in context nil

mocktracer/mockspan.go, mocktracer/mocktracer.go, mocktracer/mocktracer_test.go
My team has started using opentracing a bunch, but one problem we often run into is someone will forget to finish their started spans.  We noticed that in some cases that would cause the entire span to be dropped.  
I'm hoping to catch that in testing by providing a way to assert that every started span has a finished span, and to provide a nice error to point to which span was not finished.
=> Add started spans to mock tracer

.github/workflows/go.yml, .golangci.yml, propagation_test.go
- disable deprecated function warnings since they are used in tests & api_checker and must remain
- re-enable failing CI on lint errors
=> Fix lint warnings and re-enable failing CI on lint errors
