- examples/dapperish/dapper.go
- examples/dapperish/main.go
- opentracing/defaulttracer.go
- opentracing/noop.go
- opentracing/tracecontext.go
- opentracing/utils.go
> split the trace tags out from the core context ID in marshal/unmarshal

- examples/dapperish/main.go
- opentracing/defaulttracer.go
- opentracing/noop.go
- opentracing/opentracer.go
- opentracing/span.go
- opentracing/standardtracer/standardimpl.go
@slimsag @yurishkuro thoughts?
> set tags with help from the compiler

- opentracing/tracecontext.go
> clarify restrictedKey

- .gitignore
- Makefile
- examples/dapperish/dapper.go
- opentracing/README.md
- opentracing/defaulttracer.go
- opentracing/noop.go
- opentracing/recorder.go
- opentracing/span.go
- opentracing/standardtracer/standardimpl.go
- opentracing/tracecontext.go
- opentracing/tracer.go
> Renames OpenTracer to just Tracer; fixes minor lint issues

- examples/dapperish.go
- examples/dapperish/dapper.go
- opentracing/defaulttracer.go
- opentracing/noop.go
- opentracing/standardtracer/standardimpl.go
- opentracing/tracecontext.go
- opentracing/tracer.go
- testutils/trace_context.go
> add StartSpanWithContext, remove TraceContext.NewChild, s/TraceTag/TraceAttribute/

- README.md
- examples/dapperish.go
- examples/dapperish/trivialrecorder.go
- noop.go
- span.go
- standardtracer/raw.go
- standardtracer/standardimpl.go
See https://github.com/opentracing/opentracing-go/pull/38 and https://github.com/opentracing/opentracing.github.io/issues/30#issuecomment-173756516 .
> Like #38, but with less functionality

- standardtracer/spanpropagator.go
The sampled status of a span wasn't being recorded in PropagateSpanAsBinary, so I went ahead and added that even though I remember seeing discussion that StandardTracer might be removed.
> Fixes (span).Sampled propagation bug in StandardTracer

- .travis.yml
- README.md
Also fixes the build (#46 was a likely
accidental merge-on-red).
> Add build badge

- ext/tags_test.go
- noop.go
- propagation.go
- span.go
- utils.go
Per opentracing/opentracing.github.io#67
> Rename TraceAttribute to Baggage

- .gitignore
- README.md
> Use real import in the example

- ext/tags.go
- ext/tags_test.go
... also for the benefit of https://github.com/go-kit/kit/pull/247
> Add HTTP tags to ext/

- ext/tags.go
- ext/tags_test.go
- propagation.go
- propagation_test.go
@bensigelman I think this is not controversial
> Add helper type TextMapCarrier; Add "error" tag

- tracer.go
@dominikh care to take a quick look at this?
> Improve comments per Gitter

- ext/tags.go
- ext/tags_test.go
- tracer.go
Avoids an allocation in RPCServerOption.
> Introduce Tag type for single-tag StartSpanOptions

- ext/tags_test.go
- mocktracer/mocktracer.go
- propagation.go
- propagation_test.go
- testtracer_test.go
- tracer.go
While in the neighborhood, improve some misc comments.
See https://github.com/opentracing/opentracing.github.io/issues/98
> Add an HTTPHeaders format

- ext/tags_test.go
- mocktracer/mockspan.go
- mocktracer/mocktracer.go
- mocktracer/mocktracer_test.go
- mocktracer/propagation.go
- noop.go
- span.go
- testtracer_test.go
Per the thread at https://github.com/opentracing/opentracing.github.io/issues/106
If we go forward with this, I will clean up the comments, etc.
> RFC: immutable SpanContext

- mocktracer/mockspan.go
> Address race in nextMockID()

- ext/tags.go
- ext/tags_test.go
I added more semantic tags as describe on https://github.com/opentracing/specification/blob/master/semantic_conventions.md
> Add more semantic tags

- README.md
https://github.com/opentracing/opentracing-go/issues/167
> added SetGlobalTracer to readme

- README.md
Signed-off-by: Prakriti <prakritibansal98@gmail.com>
- Add license information to README
- Remove extra "#" from 'Non-Singleton class' heading for uniformity
> Fix minor error in README & add license information

- .github/ISSUE_TEMPLATE.md
This PR adds a standard issue template to avoid issues that can be addressed in other ways.
Ping @tedsuo @yurishkuro
> Adds issue template

- ext/tags.go
I left the SpanKindEnum one private since it seemed less reusable, but I can include it as well if preferred.
> Change SetTag helpers in ext to public
